steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    dir: 'firebase'
    args:
      - 'builds'
      - 'submit'
      - '--config=cloudbuild.yaml'
  - name: 'gcr.io/cloud-builders/gcloud'
    dir: 'android'
    args:
      - 'builds'
      - 'submit'
      - '--config=cloudbuild.yaml'
      - '--substitutions=_ANDROID_VERSION=28'
tags: [ 'cloud-builders-community' ]
options:
  logging: CLOUD_LOGGING_ONLY
