steps:
- name: 'gcr.io/cloud-builders/docker'
  dir: 'firebase'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/firebase', '.']
- name: 'gcr.io/cloud-builders/gcloud'
  dir: 'android'
  args:
    - 'builds'
    - 'submit'
    - 'config=cloudbuild.yaml'
    - '--substitutions=_ANDROID_VERSION=28'
images:
- 'gcr.io/$PROJECT_ID/firebase'
tags: ['cloud-builders-community']
